# Generated by Django 5.0.2 on 2024-05-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_product_rating_alter_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
