# Generated by Django 5.0.2 on 2024-05-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
